# Generated by Django 6.0.4 on 2026-04-21 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('thriving', 'Thriving'), ('struggling', 'Struggling'), ('failed', 'Failed')], default='thriving', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_score', models.IntegerField()),
                ('survival_status', models.CharField(max_length=50)),
                ('growth_stage', models.CharField(choices=[('callus', 'Callus forming'), ('root_init', 'Root initiation'), ('root_est', 'Root establishment'), ('shoot', 'Shoot emergence')], max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('analysed_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.plant')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.plant')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soil_temperature', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.plant')),
            ],
        ),
    ]
