# Generated by Django 6.0.7 on 2026-07-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
