# Generated by Django 6.0.7 on 2026-07-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plant_description'),
        ('api', '0002_plant_device_id'),
    ]

    operations = [
    ]
