# Generated by Django 6.0.7 on 2026-07-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_0002_plant_description_0002_plant_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
